
CREATE TABLE IF NOT EXISTS migrations (

    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS movies ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,    
    description TEXT, 
    release_date INTEGER, 

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


